import { Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

/**
 * Lightweight game audio.
 *
 * On **web** this synthesizes everything with the Web Audio API — no asset
 * files needed:
 *   • short sound effects (tap / move / hit / win / lose), and
 *   • a gentle looping background music bed (procedural arpeggio + bass).
 *
 * Mobile browsers (iOS Safari especially) block audio until the user
 * interacts, so we lazily resume the AudioContext and install a one-time
 * "first gesture" listener that unlocks + starts the music on the very first
 * tap anywhere — including the opening screen.
 *
 * On **native** (expo-av) we can't synthesize live, so we play pre-rendered
 * WAVs (assets/sounds/, generated by scripts/gen-sounds.js to match the exact
 * same tones/progression) and loop the music bed. expo-av routes through the
 * device's media-volume stream, so it follows the system volume automatically.
 *
 * A single mute flag is persisted via AsyncStorage and respected everywhere.
 */
const MUTE_KEY = 'gc_sound_muted';
const isWeb = Platform.OS === 'web';

let muted = false;
let ctx: any = null;            // AudioContext (web)

// ── Native (expo-av) ───────────────────────────────────────────────────────
// Pre-rendered assets; required statically so Metro bundles them.
const SFX_FILES: Record<string, any> = {
  tap:  require('../../assets/sounds/tap.wav'),
  move: require('../../assets/sounds/move.wav'),
  hit:  require('../../assets/sounds/hit.wav'),
  win:  require('../../assets/sounds/win.wav'),
  lose: require('../../assets/sounds/lose.wav'),
};
const MUSIC_FILE = require('../../assets/sounds/music.wav');

let nativeInit: Promise<void> | null = null;   // de-dupes concurrent loads
const nativeSfx: Record<string, any> = {};     // Sfx → Audio.Sound
let nativeMusic: any = null;                    // looping Audio.Sound

function initNative(): Promise<void> {
  if (isWeb) return Promise.resolve();
  if (!nativeInit) {
    nativeInit = (async () => {
      try {
        const { Audio } = require('expo-av');
        // Play even with the iOS ring switch off; duck other audio on Android.
        await Audio.setAudioModeAsync({ playsInSilentModeIOS: true, shouldDuckAndroid: true });
        await Promise.all(Object.entries(SFX_FILES).map(async ([k, mod]) => {
          const { sound } = await Audio.Sound.createAsync(mod, { volume: 1.0 });
          nativeSfx[k] = sound;
        }));
        const { sound } = await Audio.Sound.createAsync(MUSIC_FILE, { isLooping: true, volume: 0.6 });
        nativeMusic = sound;
      } catch { /* expo-av missing / unsupported → stay silent */ }
    })();
  }
  return nativeInit;
}

export async function loadSoundPref(): Promise<void> {
  try { muted = (await AsyncStorage.getItem(MUTE_KEY)) === '1'; } catch { /* default on */ }
  if (!isWeb) { await initNative(); if (!muted) startMusic(); }
}

export function isMuted(): boolean { return muted; }

export async function setMuted(next: boolean): Promise<void> {
  muted = next;
  try { await AsyncStorage.setItem(MUTE_KEY, next ? '1' : '0'); } catch { /* ignore */ }
  if (next) stopMusic(); else startMusic();
}

function audioCtx(): any {
  if (!isWeb || typeof window === 'undefined') return null;
  try {
    const AC = (window as any).AudioContext || (window as any).webkitAudioContext;
    if (!AC) return null;
    if (!ctx) ctx = new AC();
    if (ctx.state === 'suspended') ctx.resume();   // mobile browsers start suspended
    return ctx;
  } catch { return null; }
}

// ---------------------------------------------------------------------------
// Sound effects
// ---------------------------------------------------------------------------
export type Sfx = 'tap' | 'move' | 'hit' | 'win' | 'lose';

// Each effect is a tiny sequence of tones — cheap, no assets, "game-y".
const TONES: Record<Sfx, { freq: number; dur: number; type: string }[]> = {
  tap:  [{ freq: 440, dur: 0.05, type: 'square' }],
  move: [{ freq: 560, dur: 0.07, type: 'triangle' }],
  hit:  [{ freq: 200, dur: 0.13, type: 'sawtooth' }],
  win:  [{ freq: 523, dur: 0.11, type: 'triangle' }, { freq: 659, dur: 0.11, type: 'triangle' }, { freq: 784, dur: 0.18, type: 'triangle' }],
  lose: [{ freq: 300, dur: 0.16, type: 'sawtooth' }, { freq: 170, dur: 0.24, type: 'sawtooth' }],
};

export function playSfx(name: Sfx): void {
  if (muted) return;
  if (!isWeb) {                    // native → play the pre-rendered WAV
    initNative().then(() => { nativeSfx[name]?.replayAsync().catch(() => {}); });
    startMusic();
    return;
  }
  const c = audioCtx();
  if (!c) return;                  // unsupported → silent
  startMusic();                    // first gesture also kicks off ambient music
  let t = c.currentTime;
  for (const note of TONES[name]) {
    const osc = c.createOscillator();
    const gain = c.createGain();
    osc.type = note.type as OscillatorType;
    osc.frequency.value = note.freq;
    gain.gain.setValueAtTime(0.0001, t);
    gain.gain.exponentialRampToValueAtTime(0.5, t + 0.01);
    gain.gain.exponentialRampToValueAtTime(0.0001, t + note.dur);
    osc.connect(gain);
    gain.connect(c.destination);
    osc.start(t);
    osc.stop(t + note.dur);
    t += note.dur;
  }
}

// ---------------------------------------------------------------------------
// Background music — synthesized, looping (no audio file required)
// ---------------------------------------------------------------------------
const mtof = (m: number) => 440 * Math.pow(2, (m - 69) / 12);

// Four-bar progression: Am – F – C – G. Each bar = one bass note + a 4-step
// arpeggio of the chord tones. Mellow, low-volume, loops forever.
const BARS = [
  { bass: 45, chord: [69, 72, 76] },  // Am  (A2 · A4 C5 E5)
  { bass: 41, chord: [65, 69, 72] },  // F   (F2 · F4 A4 C5)
  { bass: 48, chord: [72, 76, 79] },  // C   (C3 · C4 E5 G5)
  { bass: 43, chord: [67, 71, 74] },  // G   (G2 · G4 B4 D5)
];
const STEP = 0.30;                 // seconds per arpeggio step (~100 BPM eighths)
const STEPS_PER_BAR = 4;

let musicGain: any = null;         // master gain for music (separate from SFX)
let musicTimer: any = null;        // lookahead scheduler interval
let nextStepTime = 0;              // when the next note should fire (ctx time)
let stepIndex = 0;                 // global step counter

function scheduleStep(c: any, step: number, time: number): void {
  const bar = BARS[Math.floor(step / STEPS_PER_BAR) % BARS.length];
  const inBar = step % STEPS_PER_BAR;

  // Bass note on the first step of each bar (longer, softer).
  if (inBar === 0) voice(c, mtof(bar.bass), 'sine', time, STEP * STEPS_PER_BAR * 0.9, 0.18);

  // Arpeggiate the chord across the bar.
  const melody = bar.chord[inBar % bar.chord.length];
  voice(c, mtof(melody), 'triangle', time, STEP * 0.85, 0.12);
}

function voice(c: any, freq: number, type: string, time: number, dur: number, peak: number): void {
  const osc = c.createOscillator();
  const gain = c.createGain();
  osc.type = type as OscillatorType;
  osc.frequency.value = freq;
  gain.gain.setValueAtTime(0.0001, time);
  gain.gain.exponentialRampToValueAtTime(peak, time + 0.04);
  gain.gain.exponentialRampToValueAtTime(0.0001, time + dur);
  osc.connect(gain);
  gain.connect(musicGain);
  osc.start(time);
  osc.stop(time + dur + 0.02);
}

export function startMusic(): void {
  if (muted) return;
  if (!isWeb) {                    // native → resume the looping bed
    initNative().then(() => { nativeMusic?.playAsync().catch(() => {}); });
    return;
  }
  const c = audioCtx();
  if (!c || musicTimer) return;    // unsupported, or already running
  if (!musicGain) {
    musicGain = c.createGain();
    musicGain.gain.value = 0.5;    // overall music level (quiet under SFX)
    musicGain.connect(c.destination);
  }
  nextStepTime = c.currentTime + 0.1;
  // Lookahead scheduler: schedule any notes due within the next 200ms.
  musicTimer = setInterval(() => {
    if (muted) { stopMusic(); return; }
    while (nextStepTime < c.currentTime + 0.2) {
      scheduleStep(c, stepIndex, nextStepTime);
      nextStepTime += STEP;
      stepIndex++;
    }
  }, 60);
}

export function stopMusic(): void {
  if (!isWeb) { nativeMusic?.pauseAsync().catch(() => {}); return; }
  if (musicTimer) { clearInterval(musicTimer); musicTimer = null; }
}

// ---------------------------------------------------------------------------
// Mobile autoplay unlock: start audio on the very first user interaction.
// ---------------------------------------------------------------------------
if (isWeb && typeof window !== 'undefined') {
  const unlock = () => {
    audioCtx();        // create + resume the context inside the gesture
    startMusic();      // begin the ambient bed (no-ops if muted)
    window.removeEventListener('pointerdown', unlock);
    window.removeEventListener('touchstart', unlock);
    window.removeEventListener('keydown', unlock);
  };
  window.addEventListener('pointerdown', unlock, { once: false });
  window.addEventListener('touchstart', unlock, { once: false });
  window.addEventListener('keydown', unlock, { once: false });
}
